### ISSUE TITLE
Can not detect GPD Win Max built-in controller while in RDP mode [BUG]

### ISSUE THREAD

**Issue by BotanKun11** [microsoft/RdpGamepad#10]
**Describe the bug**
Hello all, I have installed the Client software on my GPD Win Max and the two pieces of softwares for my receiver which is my desktop. My controller do not work while in RDP. I believe the culprit is actually my receiver as you can see from my screenshot, there is no xbox 360 controller inside the device manger. I have tried reinstalling the software on both sides and ensuring that RdpGamepadViGEm64.exe is running in the background. I have also tried removing all wireless controllers from the receiver's device manger.

**Screenshots**
![x5pVJ6qumF](https://user-images.githubusercontent.com/6925024/99019961-aa357000-25b1-11eb-8515-d3126b4d7a1f.jpg)

**OS:** 
Receiver - Windows 10 Pro Build 1909
Client - Windows 10 Home Build 2004

**Comment by jpflouret** [comment]
I don’t think the joysticks on the GPD Win Max are compatible with XInput (the programming API we use to read the gamepad values). Could you post a screenshot of the Device Manager on the client computer (the GPD Win Max)?

**Comment by BotanKun11** [comment]
![mmc_2020-11-13_18-21-11](https://user-images.githubusercontent.com/6925024/99040597-84be5b80-25dd-11eb-99ad-9a0b7f8c20c2.jpg) I believe it uses some sort of Xinput implementation for the joysticks.

**Comment by jpflouret** [comment]
Have you tried with a different client computer and/or with a USB attached Xbox One controller on the clinet?

**Comment by jpflouret** [comment]
I have no way to test this and I have not heard any other reports of this not working so I'm going to go ahead and close this issue.
