### ISSUE TITLE
Question about raw input

### ISSUE THREAD

**Issue by MarnixKuijs** [microsoft/RdpGamepad#12]
Should any application that uses raw input to deal with input be able to pickup on the pass through that RdpGamepad provides or are only xinput applications supported?

If raw input should be able to detect the passthrough what could be some reasons that the controller doesn't show up?

**Comment by jpflouret** [comment]
The way this works is that a Virtual Xbox 360 Gamepad is added to the remote system when the connection is established. In theory, any game or application that can read from an Xbox 360 gamepad should work. Note that the virtual gamepad is added but does not replace any gamepads that are physically connected to the remote computer.
