### ISSUE TITLE
[FR] Working with Anydesk?

### ISSUE THREAD

**Issue by marcoagbarreto** [microsoft/RdpGamepad#13]
I have been using Anydesk software lately, working great with games and work. I tried using the RdpGamepad but it didn't work. which makes me think. Does RdpGamepad works with Anydesk or it only works with the Remote Desktop app for windows?

I have also tried using Parsec app which works great for games and controllers are supported with the app, but I don't enjoy working on it.

It would be great to use Anydesk with the RdpGamepad plug-in.

**Comment by jpflouret** [comment]
I think you could use the concept if Anydesk has plugin support. However, this project is tightly coupled with Remote Desktop and I think you would need a new project to support Anydesk.
