### ISSUE TITLE
Smart screen reported the ReceiverInstall as not safe

### ISSUE THREAD

**Issue by emaovo** [microsoft/RdpGamepad#14]
When I try to install on windows 10 the Smart Screen blocks me signaling that the application is not safe.

**Please complete the following information:**
 - OS: Windows 10 PRO 19041

**Expected behaviour**
I should be able to install it smoothly

**Comment by jpflouret** [comment]
Confirmed that Windows Defender Smartscreen blocked installation of both client install and receiver install. Submitted files for review with Windows Securty and issue should now be resolved.
