### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xarielx** [microsoft/RdpGamepad#17]
**Describe the bug**
After following installation instructions on device manager I see "virtual xbox 360 controller" the driver is not recognized. I have installed ViGEmBus and restarted several times, remote works great on local, not on remote. 

**To Reproduce**
1. Go to '.device manager, look where the device is not installed properly'

**Expected behavior**
The device should appear properly on device manager

**Screenshots**
![image](https://user-images.githubusercontent.com/36430592/116335169-64a5e180-a7a4-11eb-80e6-2b235035ad80.png)
![image](https://user-images.githubusercontent.com/36430592/116335200-7091a380-a7a4-11eb-9316-7e09f34a32f1.png)
![image](https://user-images.githubusercontent.com/36430592/116335219-79827500-a7a4-11eb-9cc2-30a990d71c70.png)

![image](https://user-images.githubusercontent.com/36430592/116335352-bea6a700-a7a4-11eb-86cb-75d5c075042b.png)

**Please complete the following information:**
 - OS: Windows Server 2019

**Additional context**

**Comment by gmonteir** [comment]
Also having this same issue. Receiver is Windows Server 2019.

**Comment by jpflouret** [comment]
I think this is an issue with ViGEmBus on Windows server. I will file an issue with that project.

**Comment by jpflouret** [comment]
See [issue 85 in ViGEmBus](https://github.com/ViGEm/ViGEmBus/issues/85). Thanks.
