### ISSUE TITLE
Not recognized by XB1 manager or device manager

### ISSUE THREAD

**Issue by nmateja** [microsoft/RdpGamepad#2]
When following the setup steps I observe the white controller icon for the local and remote computers. 

However, when looking for the controller on the remote computer I was unable to find it within the device manager and XB1 manager did no recognize any controllers. 

I currently have windows 10 pro and am unable to use the RDP XB1 controller due to a BSOD, so I checked the "use plug-n-play devices" checkbox to see if that would help. There was no change.

**Comment by jpflouret** [comment]
@nmateja - In Device Manager, do you have an "Xbox 360 Controller for Windows"?

**Comment by jpflouret** [comment]
If you don't see the Xbox 360 Controller for Windows on Device Manager, make sure you installed the [ViGEmBus](https://github.com/ViGEm/ViGEmBus/releases/latest) drivers.

**Comment by nmateja** [comment]
Let me check.

I skipped that step since it stated
"These steps are not necessary for Windows 8.1 or 10!"

**Comment by jpflouret** [comment]
I think that only applies for the "Necessary preparations for Windows 7"

**Comment by nmateja** [comment]
Here is what I'm seeing
![Screenshot_1](https://user-images.githubusercontent.com/63258412/78594997-d8c6bd80-780e-11ea-8fde-49d0f48eeb76.png)

**Comment by nmateja** [comment]
Also, just to make sure I've got the setup correct.

The local computer is my home computer, and the remote computer is my work computer

**Comment by jpflouret** [comment]
That is correct. Your local/home computer needs the RdpGamepadClientInstall-1.0.0.exe and the remote/work computer needs both the ViGEmBus drivers and the RdpGamepadReceiverInstall-1.0.0.exe. On the remote computer it should show something like this:
![image](https://user-images.githubusercontent.com/9397098/78595749-68fd0680-77ff-11ea-9793-75151be24e94.png)

**Comment by jpflouret** [comment]
Also, if you installed the ViGEmBus drivers after starting the Remote Desktop Gamepad Receiver you may have to restart it. Close it by right clicking on the task bar notification icon and selecting Exit. Restart it from the Start Menu.

**Comment by nmateja** [comment]
Oh sweet, that worked!
![Screenshot_2](https://user-images.githubusercontent.com/63258412/78596221-01e84d80-7811-11ea-834c-f57be8c9b0af.png)

I now see the controller within the device manager and am able to use my XB1 controller with XB1 manager.

Thanks for all the help!

**Comment by jpflouret** [comment]
Nice
