### ISSUE TITLE
[FR] Mac support?

### ISSUE THREAD

**Issue by Mr-Shaan** [microsoft/RdpGamepad#23]
I am using a mac and there is no support for it.

I would like if there was support for Mac.

**Comment by jpflouret** [comment]
Unfortunately, I don't think this is currently possible. There is no macOS client that I know of that supports both Virtual Channels and that can be extended via plugins as the Windows Remote Desktop client can. Perhaps this should be a feature requrest for your favorite RDP macOS client.
