### ISSUE TITLE
[FR] Android Xinput over rdp

### ISSUE THREAD

**Issue by hovliss94** [microsoft/RdpGamepad#3]
Is it much work to have this work from android ?

**Comment by jpflouret** [comment]
Yes, that would require a completely new client implementation for Android. You would either need to implement a whole Remote Desktop client or find one client that is extensible and supports the virtual channel API.

**Comment by jpflouret** [comment]
I looked around the internet for a solution. This is unlikely to ever happen with this codebase, sorry. You could start a new project for that and use this as a base for the gamepad support. ;-)

Cheers
JP
