### ISSUE TITLE
Why didn't base your development on Remote FX USB Redirection?

### ISSUE THREAD

**Issue by FredericRobichaud** [microsoft/RdpGamepad#7]
I'm using Remote FX USB Redirection to remote use my Xbox 360 and PS4 controller but I lost my RDP connection with a Xbox One controller. Why didn't base your development on Remote FX USB Redirection?

Thanks
Fred

**Comment by jpflouret** [comment]
There are a couple reasons:

- As you have discovered, RemoteFX doesn't seem to work consistenly with an Xbox One controller.
- RemoteFX USB redirection also does not seem to work on Windows 10 Home edition and, I'm told, requires a Pro editon.
- This is very easy to install on the client and does not requre editing the group policy manually. This allows non technically-minded artists, designers and producers to install this at home with no support from our IT department.

There are probably more reasons but those are the ones I can think of off the top of my head.

Cheers
JP

**Comment by FredericRobichaud** [comment]
You indeed need Windows PRO for RemoteFX. All valid reasons. My only caveat is that I will have to switch back and forth with your plugin and RemoteFX to remote debug on my PS4 devkit. Do you want to support PS4 controller as well? ;-)

**Comment by jpflouret** [comment]
[ViGEm Bus](https://github.com/ViGEm/ViGEmBus) supports creating virtual PS4 controllers. It might be possible to add an option on the receiver to create a PS4 controller rather than an Xbox 360 controller. I do not, however, have any way of testing PS4 controllers. I would need someone else to volunteer to do that work.

**Comment by FredericRobichaud** [comment]
I can test it for you.

**Comment by jpflouret** [comment]
I need someone else to do the implementation too. I can't justify spending that time to develop PS4 controllers to my employer ;-)

**Comment by jpflouret** [comment]
Actually, go check out the ProjectAsura [fork](https://github.com/ProjectAsura/RdpGamepad). They have a DS4 implementation. You could also ask them to create a pull request!

**Comment by FredericRobichaud** [comment]
Nice!
