### ISSUE TITLE
Adding mouse support.

### ISSUE THREAD

**Issue by Fragmachine** [microsoft/RdpGamepad#9]
**Is your feature request related to a problem? Please describe.**
When working with games RDP fails due to only supporting absolute mouse movements with no way of resetting the cursor position (due to the local mouse being used instead of the remote one). What is need is relative/raw mouse data which is not restricted by the the window/screen bounds.

**Describe the solution you'd like**
It would be great if the mouse input could be similarly backdoored as the Xbox gamepad via the ViGEmBus.

**Describe alternatives you've considered**
There are a few workarounds such as

- RemoteFX with the drawback that the mouse becomes unusable on the local machine (only active in the remote window). Thus two mice is needed.
- Other remote desktop solution that has relative pointer support. Potentially expensive and might cause the cursor to lag in normal windows since essentially what happens is that the remote cursor is being activated.

**Additional context**
Ideally this is an issue that should be fixed in the RDP protocol since this would be a Windows only solutions (wouldn't work for mac or linux). Since we started working from home many months ago this has been an annoyance i.e. that the mouse can't be used when playing and debugging games and instead having to resort to key based input or switching to a controller.

**Comment by jpflouret** [comment]
Unfortunately this is not supported by ViGEmBus. Even if we could do it directly without ViGEmBus, there would still be the issue that there would be double mouse input, once from RDP in absolute coordinates and once more for relative coordinates for the game input. I think this is something the RDP protocol or Remote Desktop client needs to support directly.
